name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Run tests
        run: go test -v ./...
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/*
          retention-days: 5
